package com.example.video.pojo;

import lombok.*;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table configure
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@Table(name = "configure")
public class Configure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configure.id
     *
     * @mbg.generated
     */
    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configure.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configure.val
     *
     * @mbg.generated
     */
    private String val;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configure.remark
     *
     * @mbg.generated
     */
    private String remark;

}