package com.example.video.pojo;

import lombok.*;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table videostate
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@Table(name = "videostate")
public class VideoState {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videostate.id
     *
     * @mbg.generated
     */
    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videostate.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videostate.order
     *
     * @mbg.generated
     */
    private Integer order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videostate.cssstyle
     *
     * @mbg.generated
     */
    private String cssstyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videostate.remark
     *
     * @mbg.generated
     */
    private String remark;

}